### PR TITLE
Update SitemapUpdater.php

### PR DESCRIPTION
**Pull request by spekulatius**
the spaces weren't displayed very well before

### CODE REVIEW

**Comment by spekulatius** [comment]
Hey @phptek ,

do you want to merge this? :) Otherwise I'll close it.

Spek

**Comment by phptek** [comment]
@spekulatius thanks a lot for your input - sorry but for some reason I missed the first auto-email from Github :-(. 

While I haven't download the patch to check, AFAIK the tabs / spacings are incorrect in the module anyway. In order to comply with SilverStripe guidelines, all indents need to be tabs using a 4-space indentation (See: https://github.com/silverstripe/silverstripe-framework/blob/3/.editorconfig).

So if you raise an issue along the lines of "Convert module to SilverStripe coding guidelines", that would be v/helpful. Thanks!

**Comment by spekulatius** [comment]
@phptek I opened an issue. I'm happy to help out here. Let me know how you want to approach this.

**Comment by spekulatius** [comment]
Hello @phptek ,

do you think you want to merge this in? I opened a issue for other code style related stuff.

Spek

**Pull request closed without merging**
